In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [2]:
data = pd.read_csv(('1.txt'))

In [9]:
data = pd.read_csv(('1.txt'), delimiter='\t', sep='\t',  names = ['data'])
data = data['data'].apply(lambda x: pd.Series(list(x)))
#data.columns = np.arange(len(data.columns))
data.tail(50)

0  1  2  3  4    5    6    7    8    9   ...   90   91   92   93   94   95  \
49  0  0  0  0  1    1    0    1    1    1  ...    0    0    0    0    1    0   
50  1  1  1  1  0    0    1    0    1    0  ...    1    1    1    1    0    1   
51  0  0  0  0  0    0    0    0    1    0  ...    0    0    1    1    0    0   
52  4     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
53  0  0  0  0  0    1    0    0    0    1  ...    1    1    1    1    1    0   
54  1  1  1  1  1    1    1    1    1    1  ...    1    0    1    1    1    1   
55  1  1  1  1  1    0    1    1    1    1  ...    1    1    0    1    1    1   
56  0  0  0  0  0    0    0    1    0    0  ...    1    0    1    1    1    0   
57  1     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
58  1  1  0  0  1    0    0    1    0    0  ...    0    0    1    1    1    1   
59  2     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
60  0  0  0  0  1    0    1    0    1    0  ...    0    0    1    1    1    1   
61  1  1  1  0  1    1    1    1    0    1  ...    1    1    1    0    1    1   
62  3     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
63  1  1  1  1  0    1    1    0    0    0  ...    1    0    1    0    0    0   
64  0  0  0  1  0    0    0    0    1    0  ...    0    0    0    0    0    1   
65  1  1  1  0  1    1    0    0    1    0  ...    0    1    0    1    0    0   
66  4     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
67  1  1  1  1  1    1    1    1    0    1  ...    0    0    1    0    1    1   
68  0  0  0  0  0    0    0    0    0    0  ...    0    1    0    0    1    0   
69  1  1  0  1  1    1    0    0    0    1  ...    0    1    1    1    0    1   
70  1  1  1  1  1    1    1    1    0    1  ...    1    0    1    1    0    1   
71  1     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
72  1  1  0  0  1    0    0    1    1    0  ...    1    0    1    0    0    0   
73  2     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
74  1  1  0  0  0    0    1    1    1    1  ...    0    1    0    0    0    0   
75  0  0  0  0  1    0    1    0    0    0  ...    1    1    0    0    0    0   
76  3     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
77  0  1  1  0  0    1    0    1    1    0  ...    1    1    1    0    1    1   
78  0  0  0  0  0    0    0    1    1    0  ...    1    1    1    0    0    0   
79  0  1  1  0  0    1    0    0    1    0  ...    0    0    0    1    0    1   
80  4     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
81  0  0  0  1  1    0    1    1    0    0  ...    1    0    1    0    1    1   
82  1  1  1  0  1    1    0    1    1    0  ...    0    0    0    1    0    0   
83  1  1  1  0  0    0    1    1    1    0  ...    0    1    1    0    0    0   
84  1  1  1  1  1    1    1    0    1    0  ...    1    1    0    1    0    0   
85  1     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
86  0  0  0  0  1    0    1    1    0    0  ...    1    0    1    0    0    0   
87  2     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
88  1  0  0  1  0    0    1    0    1    0  ...    0    1    1    1    1    0   
89  1  0  0  1  0    0    0    0    1    0  ...    1    0    1    1    1    0   
90  3     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
91  0  1  0  1  0    0    1    1    1    0  ...    0    0    1    1    1    0   
92  0  0  0  0  0    0    1    1    0    1  ...    0    1    1    0    0    0   
93  1  1  0  0  0    1    0    1    1    0  ...    0    0    1    0    1    1   
94  4     1  0  0  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN   
95  1  1  0  1  1    1    0    1    1    1  ...    1    1    0    1    0    1   
96  0  0  1  1  1    1    0    1    0    1  ...    1    0    0    1    1    0   
97  1  1  1  0  0    1    0    0  


While having a constant nucleotide sequence, DNA molecules in a cell can be chemically modified in several different ways. For example, the DNA bases can be methylated, or histone proteins, around which DNA is wrapped, can be supplied with chemical tags such as acetylation. It is thought that such modifications (or epigenomic marks) define cell specialization or a cell state when a specific combination of marks regulates how genes are expressed.

In this problem, you are given genomic tracks describing the presence or absence of several epigenomic marks. Your task is to split the genomic positions into the smallest number of states so that each state corresponds to a particular combination of marks.

Input format:
The first line of the input contains t — the number of tests.

Each test consists of multiple lines. The first line contains two integers n and l — the number of sequences and their length. The remaining n lines in the test include sequences of 0 and 1, describing the epigenomic marks. All sequences have the same length l. 

Output format
Your output file should contain 2t lines with two lines per test. The first line of the answer on a test should contain the minimal number of used states ss to distinguish all combinations of marks. The second line should contain l numbers separated by spaces — the states per each position, encoded as numbers from 1 to s.



In [4]:
### solution 3 Arnaud's Method

unique_data0 = []
def scoring0(listx):
    global unique_data0
    scores = []
    for i in range(len(listx)):
        if len(unique_data0) == 0:
            unique_data0.append(listx[i])
        for j in range(len(unique_data0)):
            if unique_data0[j] ==  listx[i]:
                scores.append(j+1)
        if len(scores) == i:
            unique_data0.append(listx[i])
            scores.append(unique_data0)                         
    return scores

In [5]:
def scoring1(listx, unique_data):
    scores = []
    for i in range(len(listx)):
        for j in range(len(unique_data)):
            if unique_data[j] ==  listx[i]:
                scores.append(j+1)
    return scores

In [6]:
#10th
df1 = data.iloc[[32,33], np.r_[0:100]]
df1 = df1.astype(int)
df1

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
32   1   1   1   0   0   1   1   1   1   1  ...   1   1   1   1   1   1   1   
33   1   1   1   1   1   1   1   1   1   1  ...   0   1   1   1   1   0   1   

    97  98  99  
32   0   1   1  
33   1   1   1  

[2 rows x 100 columns]

In [263]:
#solution#1

list1 = df1.transpose().values.tolist()
unique_data1 = [list(x) for x in set(tuple(x) for x in list1)]
n = scoring1(list1,unique_data1)


print(unique_data1) #1, 2, 3, 4
print(len(unique_data1))
print('-'*50)
print(str(n).replace(',', ''))
print('-'*50)
print(list1)



[[0, 1], [1, 0], [0, 0], [1, 1]]
4
--------------------------------------------------
[4 4 4 1 1 4 4 4 4 4 1 4 4 4 4 1 1 4 4 1 4 4 4 4 4 4 1 3 3 3 1 1 4 4 4 1 4 4 1 4 4 4 4 4 4 4 1 1 1 4 4 4 4 4 1 4 1 1 1 4 1 1 1 1 4 4 2 4 4 4 4 1 4 1 3 4 1 1 4 1 2 4 2 4 1 4 4 2 4 4 2 4 4 4 4 2 4 1 4 4]
--------------------------------------------------
[[1, 1], [1, 1], [1, 1], [0, 1], [0, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [0, 1], [1, 1], [1, 1], [1, 1], [1, 1], [0, 1], [0, 1], [1, 1], [1, 1], [0, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [0, 1], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1], [1, 1], [1, 1], [1, 1], [0, 1], [1, 1], [1, 1], [0, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [0, 1], [0, 1], [0, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [0, 1], [1, 1], [0, 1], [0, 1], [0, 1], [1, 1], [0, 1], [0, 1], [0, 1], [0, 1], [1, 1], [1, 1], [1, 0], [1, 1], [1, 1], [1, 1], [1, 1], [0, 1], [1, 1], [0, 1], [0, 0], [1, 1], [0, 1], [0, 1], [1, 1], [0, 1], [1, 0], [1, 1], [1, 

In [266]:
#11th 
df2 = data.iloc[[35,36,37], np.r_[0:100]]
df2 = df2.astype(int)
df2

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
35   0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   
36   0   0   0   0   0   0   0   0   0   0  ...   0   0   1   1   0   1   0   
37   0   0   0   1   0   0   0   0   0   1  ...   0   0   1   0   0   0   0   

    97  98  99  
35   1   0   0  
36   0   0   0  
37   0   0   1  

[3 rows x 100 columns]

In [267]:
list2 = df2.transpose().values.tolist()
unique_data2 = [list(x) for x in set(tuple(x) for x in list2)]
n = scoring1(list2,unique_data2)

print(unique_data2) #1, 2, 3, 4
print(len(unique_data2))
print('-'*50)
print(str(n).replace(',', ''))
print('-'*50)
print(list2)


[[0, 1, 1], [1, 1, 1], [1, 0, 0], [0, 0, 1], [1, 0, 1], [0, 0, 0], [0, 1, 0]]
7
--------------------------------------------------
[6 6 6 4 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 6 5 6 5 5 6 6 6 6 6 1 6 6 5 6 6 6 7 5 7 6 7 6 4 6 4 4 4 7 6 6 6 6 2 6 4 6 6 5 7 6 6 4 7 7 7 6 6 5 4 6 6 6 4 6 6 6 6 6 6 6 4 4 6 6 7 4 4 6 6 6 6 6 1 7 6 7 6 3 6 4]
--------------------------------------------------
[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 1], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [1, 0, 1], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [1, 0, 1], [0, 0, 0], [1, 0, 1], [1, 0, 1], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 1, 1], [0, 0, 0], [0, 0, 0], [1, 0, 1], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 1, 0], [1, 0, 1], [0, 1, 0], [0, 0, 0], [0, 1, 0], [0, 0, 0], [0, 0, 1], [0, 0, 0], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [1, 1, 1], [0, 0, 0], [0, 0, 1], [0, 0, 0],

In [268]:
#12
df3 = data.iloc[[39,40,41,42], np.r_[0:100]]
df3 = df3.astype(int)
df3

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
39   0   0   1   1   0   1   1   0   0   0  ...   1   1   1   0   0   1   1   
40   0   0   1   1   0   1   1   1   0   1  ...   1   1   1   0   0   1   1   
41   1   1   0   0   1   0   0   0   1   0  ...   1   0   0   1   1   0   0   
42   0   0   0   1   0   0   1   0   0   0  ...   0   1   1   0   0   1   0   

    97  98  99  
39   0   1   1  
40   0   1   1  
41   1   1   0  
42   0   1   1  

[4 rows x 100 columns]

In [270]:
list3 = df3.transpose().values.tolist()
unique_data3 = [list(x) for x in set(tuple(x) for x in list3)]
s3 = scoring1(list3,unique_data3)

print(unique_data3) #1, 2, 3, 4
print(len(unique_data3))
print('-'*50)
print(str(s3).replace(',', ''))
print('-'*50)
print(list3)



[[1, 1, 0, 1], [1, 1, 1, 0], [1, 0, 0, 0], [1, 1, 0, 0], [0, 0, 0, 1], [1, 0, 1, 0], [1, 0, 0, 1], [0, 1, 0, 0], [0, 0, 1, 0], [1, 1, 1, 1], [0, 0, 1, 1], [0, 1, 0, 1]]
12
--------------------------------------------------
[9 9 4 1 9 4 1 8 9 8 1 9 8 1 1 9 9 1 1 9 8 9 1 1 8 8 9 9 1 1 5 8 1 9 9 9 8 1 8 9 7 1 6 9 9 1 9 1 8 8 9 5 7 1 7 1 8 1 9 1 9 8 9 1 10 2 1 9 11 1 1 9 3 9 1 1 12 1 9 2 1 9 5 9 9 12 12 9 4 1 2 1 1 9 9 1 4 9 10 1]
--------------------------------------------------
[[0, 0, 1, 0], [0, 0, 1, 0], [1, 1, 0, 0], [1, 1, 0, 1], [0, 0, 1, 0], [1, 1, 0, 0], [1, 1, 0, 1], [0, 1, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [1, 1, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 1, 0, 1], [1, 1, 0, 1], [0, 0, 1, 0], [0, 0, 1, 0], [1, 1, 0, 1], [1, 1, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 1, 0], [1, 1, 0, 1], [1, 1, 0, 1], [0, 1, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 1, 0], [1, 1, 0, 1], [1, 1, 0, 1], [0, 0, 0, 1], [0, 1, 0, 0], [1, 1, 0, 1], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 1, 0, 0],

In [172]:
#13 [44]
#2
# 1 2 

In [173]:
#14
df4 = data.iloc[[46,47], np.r_[0:100]]
df4 = df4.astype(int)
df4

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
46   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   0   0   
47   1   1   1   1   1   1   1   1   1   1  ...   0   1   1   1   0   0   1   

    97  98  99  
46   0   0   0  
47   1   0   1  

[2 rows x 100 columns]

In [272]:
list4 = df4.transpose().values.tolist()
unique_data4 = [list(x) for x in set(tuple(x) for x in list4)]

s4 = scoring1(list4,unique_data4)

print(unique_data4) #1, 2, 3, 4
print(len(unique_data4))
print('-'*50)
print(str(s4).replace(',', ''))
print('-'*50)
print(list4)



[[0, 1], [1, 0], [0, 0], [1, 1]]
4
--------------------------------------------------
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 3 4 4 4 4 4 4 4 1 4 4 2 2 4 2 4 3 4 4 4 4 4 4 4 3 4 4 3 4 2 2 3 4 4 2 4 4 3 2 4 4 2 4 2 3 4 4 2 1 4 4 3 2 3 4 4 1 2 3 4 4 4 1 3 4 4 4 4 4 4 1 1 2 2 2 4 4 4 2 3 1 1 3 1]
--------------------------------------------------
[[1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [0, 1], [1, 1], [0, 0], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [0, 1], [1, 1], [1, 1], [1, 0], [1, 0], [1, 1], [1, 0], [1, 1], [0, 0], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [0, 0], [1, 1], [1, 1], [0, 0], [1, 1], [1, 0], [1, 0], [0, 0], [1, 1], [1, 1], [1, 0], [1, 1], [1, 1], [0, 0], [1, 0], [1, 1], [1, 1], [1, 0], [1, 1], [1, 0], [0, 0], [1, 1], [1, 1], [1, 0], [0, 1], [1, 1], [1, 1], [0, 0], [1, 0], [0, 0], [1, 1], [1, 1], [0, 1], [1, 0], [0, 0], [1, 1], [1, 1], [1, 1], [0, 1], [0, 0], [1, 1], [1, 1], [1, 

In [177]:
#15
df5 = data.iloc[[49,50,51], np.r_[0:100]]
df5 = df5.astype(int)
df5

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
49   0   0   0   0   1   1   0   1   1   1  ...   0   0   0   0   1   0   1   
50   1   1   1   1   0   0   1   0   1   0  ...   1   1   1   1   0   1   1   
51   0   0   0   0   0   0   0   0   1   0  ...   0   0   1   1   0   0   1   

    97  98  99  
49   1   0   1  
50   0   1   0  
51   0   1   0  

[3 rows x 100 columns]

In [273]:
list5 = df5.transpose().values.tolist()
unique_data5 = [list(x) for x in set(tuple(x) for x in list5)]


s5 = scoring3(list5,unique_data5)


print(unique_data5) #1, 2, 3, 4
print(len(unique_data5))
print('-'*50)
print(str(s5).replace(',', ''))
print('-'*50)
print(list5)


[[1, 1, 0], [0, 1, 1], [0, 1, 0], [1, 0, 0], [0, 0, 1], [1, 0, 1], [0, 0, 0], [1, 1, 1]]
8
--------------------------------------------------
[3 3 3 3 4 4 3 4 8 4 3 4 4 4 3 3 3 8 3 8 2 8 3 4 3 4 3 4 1 3 3 4 4 4 2 4 2 4 4 3 2 4 3 4 7 6 3 3 8 7 3 3 3 3 6 8 3 2 4 8 2 4 4 7 4 3 1 4 2 4 4 4 7 8 1 1 4 1 3 4 4 4 1 5 4 3 3 8 4 1 3 3 2 2 4 3 8 4 2 4]
--------------------------------------------------
[[0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 1], [1, 0, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 1, 1], [0, 1, 0], [1, 1, 1], [0, 1, 1], [1, 1, 1], [0, 1, 0], [1, 0, 0], [0, 1, 0], [1, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [0, 1, 1], [1, 0, 0], [0, 1, 1], [1, 0, 0], [1, 0, 0], [0, 1, 0], [0, 1, 1], [1, 0, 0], [0, 1, 0], [1, 0, 0], [0, 0, 0], [1, 0, 1], [0, 1, 0], [0, 1, 0], [1, 1, 1], [0, 0, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 1],

In [186]:
#16
df6 = data.iloc[[53,54,55,56], np.r_[0:100]]
df6 = df6.astype(int)
df6

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
53   0   0   0   0   0   1   0   0   0   1  ...   1   1   1   1   1   0   1   
54   1   1   1   1   1   1   1   1   1   1  ...   1   0   1   1   1   1   1   
55   1   1   1   1   1   0   1   1   1   1  ...   1   1   0   1   1   1   1   
56   0   0   0   0   0   0   0   1   0   0  ...   1   0   1   1   1   0   0   

    97  98  99  
53   1   0   1  
54   1   1   1  
55   1   0   0  
56   0   1   0  

[4 rows x 100 columns]

In [274]:
list6 = df6.transpose().values.tolist()
unique_data6 = [list(x) for x in set(tuple(x) for x in list6)]
unique_data6

s6 = scoring1(list6,unique_data6)

print(unique_data6) #1, 2, 3, 4
print(len(unique_data6))
print('-'*50)
print(str(s6).replace(',', ''))
print('-'*50)
print(list6)

[[1, 1, 0, 1], [1, 1, 1, 0], [1, 0, 0, 0], [1, 1, 0, 0], [0, 1, 1, 1], [1, 0, 1, 0], [0, 0, 0, 1], [1, 1, 1, 1], [0, 1, 0, 0], [0, 0, 1, 0], [1, 0, 0, 1], [0, 1, 1, 0], [0, 0, 0, 0], [0, 1, 0, 1], [0, 0, 1, 1]]
15
--------------------------------------------------
[12 12 12 12 12 4 12 5 12 2 5 14 12 12 12 12 13 3 8 6 12 12 12 12 3 12 12 6 9 4 14 12 12 15 8 12 5 13 12 12 12 14 3 3 12 13 5 12 12 3 12 12 12 6 12 5 12 13 2 9 10 11 12 8 4 8 12 7 7 14 2 12 15 10 10 8 1 14 12 10 8 14 12 12 14 12 9 10 8 13 8 6 1 8 8 12 2 2 14 4]
--------------------------------------------------
[[0, 1, 1, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 1, 1, 0], [1, 1, 0, 0], [0, 1, 1, 0], [0, 1, 1, 1], [0, 1, 1, 0], [1, 1, 1, 0], [0, 1, 1, 1], [0, 1, 0, 1], [0, 1, 1, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0], [1, 0, 0, 0], [1, 1, 1, 1], [1, 0, 1, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 1, 1, 0], [1, 0, 0, 0], [0, 1, 1, 0], [0, 1, 1, 0], [1, 0, 1, 0], [0, 1, 0, 0], [1, 1, 0, 0], [

In [ ]:
#17 [58]
#1
#1 2 

In [193]:
#18
df7 = data.iloc[[60,61], np.r_[0:100]]
df7 = df7.astype(int)
df7

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
60   0   0   0   0   1   0   1   0   1   0  ...   0   0   1   1   1   1   1   
61   1   1   1   0   1   1   1   1   0   1  ...   1   1   1   0   1   1   1   

    97  98  99  
60   1   0   0  
61   0   0   1  

[2 rows x 100 columns]

In [275]:
list7 = df7.transpose().values.tolist()
unique_data7 = [list(x) for x in set(tuple(x) for x in list7)]

s7 = scoring3(list7,unique_data7)

print(unique_data7) #1, 2, 3, 4
print(len(unique_data7))
print('-'*50)
print(str(s7).replace(',', ''))
print('-'*50)
print(list7)



[[0, 1], [1, 0], [0, 0], [1, 1]]
4
--------------------------------------------------
[1 1 1 3 4 1 4 1 2 1 2 1 2 1 3 1 1 1 4 1 2 2 3 1 4 1 4 3 4 3 2 4 3 3 4 2 1 1 1 1 1 4 3 1 1 2 2 4 2 1 4 1 1 4 4 2 2 1 4 3 3 4 3 1 1 4 3 3 4 1 2 2 2 2 1 1 3 4 1 1 3 3 4 1 3 1 2 3 2 2 1 1 4 2 4 4 4 2 3 1]
--------------------------------------------------
[[0, 1], [0, 1], [0, 1], [0, 0], [1, 1], [0, 1], [1, 1], [0, 1], [1, 0], [0, 1], [1, 0], [0, 1], [1, 0], [0, 1], [0, 0], [0, 1], [0, 1], [0, 1], [1, 1], [0, 1], [1, 0], [1, 0], [0, 0], [0, 1], [1, 1], [0, 1], [1, 1], [0, 0], [1, 1], [0, 0], [1, 0], [1, 1], [0, 0], [0, 0], [1, 1], [1, 0], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [1, 1], [0, 0], [0, 1], [0, 1], [1, 0], [1, 0], [1, 1], [1, 0], [0, 1], [1, 1], [0, 1], [0, 1], [1, 1], [1, 1], [1, 0], [1, 0], [0, 1], [1, 1], [0, 0], [0, 0], [1, 1], [0, 0], [0, 1], [0, 1], [1, 1], [0, 0], [0, 0], [1, 1], [0, 1], [1, 0], [1, 0], [1, 0], [1, 0], [0, 1], [0, 1], [0, 0], [1, 1], [0, 1], [0, 1], [0, 0], [0, 0], [1, 

In [12]:
#global function to use 


def full_f(df,data ):
    df = data
    df = df.astype(int)
    listx = df.transpose().values.tolist()
    unique_data = [list(x) for x in set(tuple(x) for x in listx)]
    s = scoring1(listx,unique_data)
    return  print(unique_data), print(len(unique_data)), print('-'*50), print(str(s).replace(',', '')), print('-'*50), print(listx)






In [13]:
#19
df8 = data.iloc[[63,64, 65], np.r_[0:100]]
df8 = df8.astype(int)

a = full_f(df = df8, data = data.iloc[[63,64,65], np.r_[0:100]], )

[[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 0, 0], [0, 0, 1], [1, 0, 1], [0, 0, 0], [0, 1, 0]]
8
--------------------------------------------------
[6 6 6 1 5 6 4 7 2 7 5 5 1 6 8 7 4 6 6 4 4 3 2 6 8 1 4 5 3 7 4 5 5 2 5 6 6 2 4 2 1 8 5 7 8 7 4 3 2 6 6 8 6 1 2 3 6 6 8 8 1 7 6 8 4 3 4 2 8 1 1 4 1 1 7 7 3 2 4 7 4 1 1 1 5 2 5 3 8 1 4 5 4 5 7 8 4 1 1 8]
--------------------------------------------------
[[1, 0, 1], [1, 0, 1], [1, 0, 1], [1, 1, 0], [0, 0, 1], [1, 0, 1], [1, 0, 0], [0, 0, 0], [0, 1, 1], [0, 0, 0], [0, 0, 1], [0, 0, 1], [1, 1, 0], [1, 0, 1], [0, 1, 0], [0, 0, 0], [1, 0, 0], [1, 0, 1], [1, 0, 1], [1, 0, 0], [1, 0, 0], [1, 1, 1], [0, 1, 1], [1, 0, 1], [0, 1, 0], [1, 1, 0], [1, 0, 0], [0, 0, 1], [1, 1, 1], [0, 0, 0], [1, 0, 0], [0, 0, 1], [0, 0, 1], [0, 1, 1], [0, 0, 1], [1, 0, 1], [1, 0, 1], [0, 1, 1], [1, 0, 0], [0, 1, 1], [1, 1, 0], [0, 1, 0], [0, 0, 1], [0, 0, 0], [0, 1, 0], [0, 0, 0], [1, 0, 0], [1, 1, 1], [0, 1, 1], [1, 0, 1], [1, 0, 1], [0, 1, 0], [1, 0, 1], [1, 1, 0], [0, 1, 1],

In [14]:
##20
df9 = data.iloc[[67,68, 69,70], np.r_[0:100]]
df9 = df9.astype(int)

a = full_f(df = df9, data = data.iloc[[67,68, 69,70], np.r_[0:100]], )

[[1, 0, 1, 1], [1, 1, 0, 1], [1, 1, 1, 0], [1, 0, 0, 0], [1, 1, 0, 0], [0, 0, 0, 1], [0, 1, 1, 1], [1, 0, 1, 0], [1, 1, 1, 1], [1, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 0], [0, 1, 1, 0], [0, 1, 0, 1], [0, 0, 1, 1]]
16
--------------------------------------------------
[1 1 10 1 1 1 10 10 13 1 9 1 9 6 10 5 1 1 1 5 1 6 3 13 1 1 11 12 10 9 5 4 12 14 15 13 1 14 7 14 1 5 4 1 2 1 8 1 9 10 11 3 1 3 6 4 2 3 8 1 10 11 14 5 10 13 1 1 10 6 12 8 9 16 1 14 1 1 12 10 9 3 8 1 1 13 16 10 1 3 6 14 1 16 5 1 14 4 9 10]
--------------------------------------------------
[[1, 0, 1, 1], [1, 0, 1, 1], [1, 0, 0, 1], [1, 0, 1, 1], [1, 0, 1, 1], [1, 0, 1, 1], [1, 0, 0, 1], [1, 0, 0, 1], [0, 0, 0, 0], [1, 0, 1, 1], [1, 1, 1, 1], [1, 0, 1, 1], [1, 1, 1, 1], [0, 0, 0, 1], [1, 0, 0, 1], [1, 1, 0, 0], [1, 0, 1, 1], [1, 0, 1, 1], [1, 0, 1, 1], [1, 1, 0, 0], [1, 0, 1, 1], [0, 0, 0, 1], [1, 1, 1, 0], [0, 0, 0, 0], [1, 0, 1, 1], [1, 0, 1, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 1], [1, 1, 1, 1], [1, 1, 0, 0]

In [15]:
##22
df22 = data.iloc[[74,75], np.r_[0:100]]
df22 = df22.astype(int)

a = full_f(df = df22, data = data.iloc[[74,75], np.r_[0:100]], )

[[0, 1], [1, 0], [0, 0], [1, 1]]
4
--------------------------------------------------
[2 2 3 3 1 3 4 2 2 2 3 3 3 2 2 4 4 3 2 4 2 2 3 3 1 1 4 1 3 1 2 3 4 3 3 2 3 3 4 2 1 4 3 2 2 1 3 4 3 3 3 4 2 2 3 2 2 3 4 3 2 2 2 2 4 4 3 1 3 4 3 2 4 1 2 1 2 1 3 1 3 3 4 2 2 4 1 2 1 1 1 4 3 3 3 3 3 3 3 3]
--------------------------------------------------
[[1, 0], [1, 0], [0, 0], [0, 0], [0, 1], [0, 0], [1, 1], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [1, 0], [1, 0], [1, 1], [1, 1], [0, 0], [1, 0], [1, 1], [1, 0], [1, 0], [0, 0], [0, 0], [0, 1], [0, 1], [1, 1], [0, 1], [0, 0], [0, 1], [1, 0], [0, 0], [1, 1], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [1, 1], [1, 0], [0, 1], [1, 1], [0, 0], [1, 0], [1, 0], [0, 1], [0, 0], [1, 1], [0, 0], [0, 0], [0, 0], [1, 1], [1, 0], [1, 0], [0, 0], [1, 0], [1, 0], [0, 0], [1, 1], [0, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 1], [1, 1], [0, 0], [0, 1], [0, 0], [1, 1], [0, 0], [1, 0], [1, 1], [0, 1], [1, 0], [0, 1], [1, 0], [0, 1], [0, 0], [0, 1], [0, 0], [0, 0], [1, 

In [16]:
##23
df23 = data.iloc[[77,78,79], np.r_[0:100]]
df23 = df23.astype(int)

a = full_f(df = df23, data = data.iloc[[77,78,79], np.r_[0:100]], )

[[1, 1, 0], [0, 1, 1], [0, 1, 0], [1, 0, 0], [0, 0, 1], [1, 0, 1], [0, 0, 0], [1, 1, 1]]
8
--------------------------------------------------
[7 6 6 7 7 6 7 1 8 7 2 1 4 2 5 2 8 1 4 7 1 8 6 8 6 2 4 2 2 1 1 1 4 6 2 8 8 4 3 2 8 5 4 3 3 3 2 4 7 7 8 3 7 8 5 1 2 2 6 1 4 3 5 1 8 5 5 2 6 3 3 6 4 4 4 7 4 7 4 7 3 8 2 7 1 8 2 2 7 2 1 1 1 5 4 6 8 1 2 5]
--------------------------------------------------
[[0, 0, 0], [1, 0, 1], [1, 0, 1], [0, 0, 0], [0, 0, 0], [1, 0, 1], [0, 0, 0], [1, 1, 0], [1, 1, 1], [0, 0, 0], [0, 1, 1], [1, 1, 0], [1, 0, 0], [0, 1, 1], [0, 0, 1], [0, 1, 1], [1, 1, 1], [1, 1, 0], [1, 0, 0], [0, 0, 0], [1, 1, 0], [1, 1, 1], [1, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1], [1, 0, 0], [0, 1, 1], [0, 1, 1], [1, 1, 0], [1, 1, 0], [1, 1, 0], [1, 0, 0], [1, 0, 1], [0, 1, 1], [1, 1, 1], [1, 1, 1], [1, 0, 0], [0, 1, 0], [0, 1, 1], [1, 1, 1], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 1], [1, 0, 0], [0, 0, 0], [0, 0, 0], [1, 1, 1], [0, 1, 0], [0, 0, 0], [1, 1, 1], [0, 0, 1],

In [17]:
##24
df24 = data.iloc[[81,82,83,84], np.r_[0:100]]
df24 = df24.astype(int)

a = full_f(df = df24, data = data.iloc[[81,82,83,84], np.r_[0:100]], )

[[1, 1, 0, 1], [1, 0, 1, 1], [1, 1, 1, 0], [1, 0, 0, 0], [1, 1, 0, 0], [0, 1, 1, 1], [0, 0, 0, 1], [1, 0, 1, 0], [1, 0, 0, 1], [1, 1, 1, 1], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 0], [0, 1, 1, 0], [0, 1, 0, 1], [0, 0, 1, 1]]
16
--------------------------------------------------
[6 6 6 9 1 15 2 3 6 13 10 15 1 2 1 6 1 2 13 2 16 6 14 14 3 3 4 6 9 9 1 14 9 6 3 7 7 5 2 3 15 3 7 11 3 1 6 1 11 4 4 6 7 3 12 14 7 14 15 16 3 6 13 14 6 10 1 2 9 6 7 4 12 15 6 2 8 4 9 1 11 11 8 16 7 15 1 1 14 7 9 16 8 15 4 4 7 11 9 4]
--------------------------------------------------
[[0, 1, 1, 1], [0, 1, 1, 1], [0, 1, 1, 1], [1, 0, 0, 1], [1, 1, 0, 1], [0, 1, 0, 1], [1, 0, 1, 1], [1, 1, 1, 0], [0, 1, 1, 1], [0, 0, 0, 0], [1, 1, 1, 1], [0, 1, 0, 1], [1, 1, 0, 1], [1, 0, 1, 1], [1, 1, 0, 1], [0, 1, 1, 1], [1, 1, 0, 1], [1, 0, 1, 1], [0, 0, 0, 0], [1, 0, 1, 1], [0, 0, 1, 1], [0, 1, 1, 1], [0, 1, 1, 0], [0, 1, 1, 0], [1, 1, 1, 0], [1, 1, 1, 0], [1, 0, 0, 0], [0, 1, 1, 1], [1, 0, 0, 1], [1, 0, 0, 1], [1, 1, 0, 1], [0,

In [18]:
##26
df26 = data.iloc[[88,89], np.r_[0:100]]
df26 = df26.astype(int)

a = full_f(df = df26, data = data.iloc[[88,89], np.r_[0:100]], )

[[0, 1], [1, 0], [0, 0], [1, 1]]
4
--------------------------------------------------
[4 3 3 4 3 3 2 3 4 3 2 3 1 4 3 3 2 2 1 4 4 3 2 1 2 4 1 2 3 2 4 3 1 2 2 2 1 4 4 1 1 4 3 1 1 1 1 1 2 2 2 1 2 1 4 2 4 3 4 4 3 1 1 3 2 4 2 1 1 2 1 1 1 1 3 1 1 1 3 4 2 3 3 4 1 2 4 4 3 4 1 2 4 4 4 3 2 3 3 2]
--------------------------------------------------
[[1, 1], [0, 0], [0, 0], [1, 1], [0, 0], [0, 0], [1, 0], [0, 0], [1, 1], [0, 0], [1, 0], [0, 0], [0, 1], [1, 1], [0, 0], [0, 0], [1, 0], [1, 0], [0, 1], [1, 1], [1, 1], [0, 0], [1, 0], [0, 1], [1, 0], [1, 1], [0, 1], [1, 0], [0, 0], [1, 0], [1, 1], [0, 0], [0, 1], [1, 0], [1, 0], [1, 0], [0, 1], [1, 1], [1, 1], [0, 1], [0, 1], [1, 1], [0, 0], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [1, 0], [1, 0], [1, 0], [0, 1], [1, 0], [0, 1], [1, 1], [1, 0], [1, 1], [0, 0], [1, 1], [1, 1], [0, 0], [0, 1], [0, 1], [0, 0], [1, 0], [1, 1], [1, 0], [0, 1], [0, 1], [1, 0], [0, 1], [0, 1], [0, 1], [0, 1], [0, 0], [0, 1], [0, 1], [0, 1], [0, 0], [1, 1], [1, 0], [0, 0], [0, 

In [19]:
##27
df27 = data.iloc[[91,92,93], np.r_[0:100]]
df27 = df27.astype(int)

a = full_f(df = df27, data = data.iloc[[91,92,93], np.r_[0:100]], )

[[1, 1, 0], [0, 1, 1], [0, 1, 0], [1, 0, 0], [0, 0, 1], [1, 0, 1], [0, 0, 0], [1, 1, 1]]
8
--------------------------------------------------
[5 6 7 4 7 5 1 8 6 3 5 4 5 7 4 5 6 4 6 4 8 4 4 5 8 3 2 4 6 6 1 1 5 2 5 2 4 7 8 2 1 2 1 8 6 4 3 1 4 8 4 4 6 6 7 1 7 8 8 7 3 7 5 6 4 5 6 8 6 7 7 2 4 1 2 2 3 5 4 1 8 8 2 5 2 3 1 1 4 4 7 3 8 4 6 5 5 8 5 5]
--------------------------------------------------
[[0, 0, 1], [1, 0, 1], [0, 0, 0], [1, 0, 0], [0, 0, 0], [0, 0, 1], [1, 1, 0], [1, 1, 1], [1, 0, 1], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 0, 0], [1, 0, 0], [0, 0, 1], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 1, 1], [1, 0, 0], [1, 0, 0], [0, 0, 1], [1, 1, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 0, 1], [1, 1, 0], [1, 1, 0], [0, 0, 1], [0, 1, 1], [0, 0, 1], [0, 1, 1], [1, 0, 0], [0, 0, 0], [1, 1, 1], [0, 1, 1], [1, 1, 0], [0, 1, 1], [1, 1, 0], [1, 1, 1], [1, 0, 1], [1, 0, 0], [0, 1, 0], [1, 1, 0], [1, 0, 0], [1, 1, 1], [1, 0, 0], [1, 0, 0], [1, 0, 1], [1, 0, 1], [0, 0, 0],

In [20]:
##28
df28 = data.iloc[[95,96,97,98], np.r_[0:100]]
df28 = df28.astype(int)

a = full_f(df = df28, data = data.iloc[[95,96,97,98], np.r_[0:100]], )

[[1, 0, 1, 1], [1, 1, 0, 1], [1, 0, 0, 0], [1, 1, 1, 0], [1, 0, 1, 0], [1, 1, 0, 0], [0, 0, 0, 1], [0, 1, 1, 1], [1, 1, 1, 1], [1, 0, 0, 1], [0, 1, 0, 0], [0, 0, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0], [0, 0, 1, 1], [0, 1, 0, 1]]
16
--------------------------------------------------
[5 1 13 6 6 9 7 6 10 2 11 1 5 12 10 15 6 9 15 12 13 13 1 12 12 8 9 3 6 9 6 2 7 16 13 10 12 1 3 11 8 1 3 15 13 15 10 14 8 15 5 8 4 12 13 15 3 8 4 8 8 11 15 2 5 11 16 15 8 15 16 10 7 7 4 15 3 8 15 9 7 5 2 8 2 2 16 5 1 4 6 10 12 4 8 1 9 1 4 12]
--------------------------------------------------
[[1, 0, 1, 0], [1, 0, 1, 1], [0, 1, 1, 0], [1, 1, 0, 0], [1, 1, 0, 0], [1, 1, 1, 1], [0, 0, 0, 1], [1, 1, 0, 0], [1, 0, 0, 1], [1, 1, 0, 1], [0, 1, 0, 0], [1, 0, 1, 1], [1, 0, 1, 0], [0, 0, 1, 0], [1, 0, 0, 1], [0, 0, 1, 1], [1, 1, 0, 0], [1, 1, 1, 1], [0, 0, 1, 1], [0, 0, 1, 0], [0, 1, 1, 0], [0, 1, 1, 0], [1, 0, 1, 1], [0, 0, 1, 0], [0, 0, 1, 0], [0, 1, 1, 1], [1, 1, 1, 1], [1, 0, 0, 0], [1, 1, 0, 0], [1, 1, 1, 1], [1, 1, 